server:
  port: 8080
  tomcat:
    uri-encoding: GBK
spring:
  redis:
    host: 127.0.0.1
    port: 6379
  http:
    encoding:
      force: true
      charset: GBK
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3366/hjdj_wxgzh?serverTimezone=UTC&useSSL=false
    username: root
    password: 123
